### ISSUE TITLE
Where to add example configuration snippits?

### ISSUE THREAD

**Issue by ypid** [debops/debops-playbooks#180]
Good evening

I am using a lot of DebOps roles lately and have created some configuration snippets which I think could also come in handy for others. Is there a good place to add them somewhere.

Example. Using the [debops.apt_preferences](https://github.com/debops/ansible-apt_preferences) role, I configured apt preferences for my systems to handle various sources in the sources.list:

```YAML
apt_preferences_list:
  - package: '*'
    suffix: '_Debian'
    raw: |
      Explanation: Configure the installed release higher as the default (500) so that those packages are preferred.
      Package: *
      Pin: release o=Debian,n={{ ansible_distribution_release }}
      Pin-Priority: 600

      Explanation: The default priority of packages from backports is 100 which is even lower then testing and unstable (500).
      Explanation: Prefer backports over testing and unstable but don’t automatically upgrade to it.
      Package: *
      Pin: release o=Debian Backports,n={{ ansible_distribution_release }}-backports
      Pin-Priority: 400

      Explanation: Install packages from testing if no package with the same name is available in release archives or backports or other archives.
      Package: *
      Pin: release o=Debian,a=testing
      Pin-Priority: 300

      Explanation: Only install packages from unstable if explicitly asked for or the package is pined.
      Package: *
      Pin: release o=Debian,a=unstable
      Pin-Priority: -1

      Explanation: Only install packages from experimental if explicitly asked for or the package is pined.
      Package: *
      Pin: release o=Debian,a=experimental
      Pin-Priority: -1
```

I also worked a bit on ownCloud tuning. I would propose to add an directory to each role for example configurations which might be useful for that role. What do you think?
