### ISSUE TITLE
Make group `distribution_$distri` and `distribution_$distri_$release` avalable.

### ISSUE THREAD

**Issue by ypid** [debops/debops-playbooks#205]
I use these to define apt pinnings for Debian which make no sense on other distros like Ubuntu. For this I have in a pre task:

```YAML
- name: Group hosts by distribution
  group_by:
    key: 'distribution_{{ ansible_distribution }}'
  changed_when: False

- name: Group hosts by distribution and release
  group_by:
    key: 'distribution_{{ ansible_distribution }}_{{ ansible_distribution_release }}'
  changed_when: False
```

Would it make sense to add this to DebOps?

See https://docs.ansible.com/ansible/playbooks_best_practices.html#operating-system-and-distribution-variance
