### ISSUE TITLE
Depend variables default way to indicate source role name

### ISSUE THREAD

**Issue by ypid** [debops/debops-playbooks#296]
Various roles in DebOps expose dependency variables for other roles to use. Example [`ferm__dependent_rules`](https://docs.debops.org/en/latest/ansible/roles/ansible-ferm/docs/defaults.html#envvar-ferm__dependent_rules) of [debops.ferm](https://github.com/debops/ansible-ferm/).

There have been a number of changes in the format how to do this.

The current format is:

```YAML
  - something: 'something'
    role: 'ROLE_NAME'
# and
  - something: 'something'
    role: 'nginx'
```

This applies for all roles. Other keys like `by_role` are deprecated.

**Comment by ypid** [comment]
@drybjed Or

```YAML
  - something: 'something'
    role: 'debops.nginx'
```

?

**Comment by drybjed** [comment]
Using `debops.nginx` is probably better since it's more explicit, and there could be other `nginx` roles in use.

**Comment by ypid** [comment]
It is just not widely used in DebOps yet. Probably also because file names are generated based on that. I would propose to sanitize the `role` (name) then with (`replace(".", "_")`). Sounds good?

**Comment by drybjed** [comment]
Sure, sounds good.

**Comment by ypid** [comment]
Updated my first comment with the currently approved version based on a discussion with @drybjed. Example:

```YAML
  - something: 'something'
    by_role: 'ROLE_OWNER.ROLE_NAME'
# and
  - something: 'something'
    by_role:: 'debops.nginx'
```
